name:                aria2c-rpc
version:             0.1.0.0
github:              "rmanne/aria2c-rpc"
license:             BSD3
author:              "Rahul Manne"
maintainer:          "rahul_manne@hotmail.com"
copyright:           "2020 Rahul Manne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aria2c-rpc#readme>

dependencies:
- base >= 4.7 && < 5
- http-conduit
- aeson
- uuid
- transformers
- vector
- text
- bytestring
- websockets
- containers
- network

default-extensions:
- LambdaCase
- OverloadedStrings
- TupleSections
- MultiWayIf
- RecordWildCards

library:
  source-dirs: src

executables:
  aria2c-rpc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aria2c-rpc

tests:
  aria2c-rpc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aria2c-rpc
